using Dhole.Content.Application.Abstractions.Cache;using Dhole.Content.Application.Abstractions.Mongo;namespace Dhole.Content.Worker.Streams;
internal sealed class ContentItemCreatedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<ContentItemCreatedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.item.created";protected override bool InvalidateContent=>true;}
internal sealed class ContentItemUpdatedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<ContentItemUpdatedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.item.updated";protected override bool InvalidateContent=>true;}
internal sealed class ContentItemReviewRequestedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<ContentItemReviewRequestedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.item.review-requested";protected override bool InvalidateContent=>true;}
internal sealed class ContentItemPublishedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<ContentItemPublishedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.item.published";protected override bool InvalidateContent=>true;}
internal sealed class ContentItemScheduledStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<ContentItemScheduledStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.item.scheduled";protected override bool InvalidateContent=>true;}
internal sealed class ContentItemUnpublishedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<ContentItemUnpublishedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.item.unpublished";protected override bool InvalidateContent=>true;}
internal sealed class ContentItemArchivedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<ContentItemArchivedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.item.archived";protected override bool InvalidateContent=>true;}
internal sealed class ContentItemDeletedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<ContentItemDeletedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.item.deleted";protected override bool InvalidateContent=>true;}
internal sealed class ContentItemRevisionRestoredStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<ContentItemRevisionRestoredStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.item.revision-restored";protected override bool InvalidateContent=>true;}
internal sealed class TaxonomyCreatedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<TaxonomyCreatedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.taxonomy.created";}
internal sealed class TaxonomyUpdatedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<TaxonomyUpdatedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.taxonomy.updated";}
internal sealed class TaxonomyDeletedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<TaxonomyDeletedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.taxonomy.deleted";}
internal sealed class MediaCreatedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<MediaCreatedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.media.created";}
internal sealed class MediaDeletedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<MediaDeletedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.media.deleted";}
internal sealed class MenuChangedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<MenuChangedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.menu.changed";protected override bool InvalidateMenu=>true;}
internal sealed class SettingChangedStreamHandler(IContentCacheService c,IContentChangeSnapshotWriter s,ILogger<SettingChangedStreamHandler> l):ContentProjectionStreamHandlerBase(c,s,l){public override string MessageType=>"content.setting.changed";protected override bool InvalidateSettings=>true;}
